name: Migrate Garmin CN to Garmin Global

on:
  workflow_dispatch:

env:
  AESKEY: ${{ secrets.AESKEY }}
  BARK_KEY: ${{ secrets.BARK_KEY }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  WECOM_WEBHOOK_URL: ${{ secrets.WECOM_WEBHOOK_URL }}
  GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
  GARMIN_GLOBAL_USERNAME: ${{ secrets.GARMIN_GLOBAL_USERNAME }}
  GARMIN_GLOBAL_PASSWORD: ${{ secrets.GARMIN_GLOBAL_PASSWORD }}
  GARMIN_MIGRATE_NUM: ${{ secrets.GARMIN_MIGRATE_NUM }}
  GARMIN_MIGRATE_START: ${{ secrets.GARMIN_MIGRATE_START }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Migrate Garmin CN to Garmin Global
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      # 从缓存恢复 Session 数据库
      - name: Restore Session Cache
        uses: actions/cache@v4
        with:
          path: db/garmin.db
          key: garmin-session-${{ github.repository }}-migrate-cn2global
          restore-keys: |
            garmin-session-${{ github.repository }}-migrate-cn2global

      - run: yarn

      - run: yarn migrate:cn2global
